export const ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";

export const wiringA = "BDFHJLCPRTXVZNYEIWGAKMUSQO";
export const wiringB = "AJDKSIRUXBLHWTMCQGZNPYFVOE";
export const wiringC = "EKMFLGDQVZNTOWYHXUSPAIBRCJ";
export const wiringRev = "YRUHQSLDPXNGOKMIEBFZCWVJAT";